backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java, backend/src/main/java/site/coduo/pairroom/controller/PairRoomErrorController.java, backend/src/main/java/site/coduo/pairroom/domain/PairRoom.java, backend/src/main/java/site/coduo/pairroom/dto/ReadPairRoom.java
- closes: (이슈 번호)
cors 오류 해결 및 api 명세서 대로 json 파라미터 이름 변경
=> [BE] CORS 오류 해결

backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java, backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java, backend/src/main/java/site/coduo/pairroom/dto/CreatePairRoom.java, backend/src/main/java/site/coduo/pairroom/dto/PairRoomRequest.java, backend/src/main/java/site/coduo/pairroom/dto/PairRoomResponse.java, backend/src/main/java/site/coduo/pairroom/dto/ReadPairRoom.java
- closes: #26
- 컨트롤러 문서화 용도의 인터페이스 생성
- DTO 문서화
문서화 내용 중에 잘못된 부분이 있으면 말씀해 주세요!
=> [BE] 페어룸 생성 & 조회 문서화

backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java, backend/src/main/java/site/coduo/referencelink/exception/InvalidUrlFormatException.java, backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java, backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkRepository.java, backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java, backend/src/test/java/site/coduo/referencelink/domain/ReferenceLinkEntityTest.java, backend/src/test/java/site/coduo/referencelink/domain/ReferenceLinkTest.java, backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
- closes: #37 
레퍼런스 링크 url 빈 값 검증 추가
=> [BE] ReferenceLink 검증 추가

frontend/package.json, frontend/src/App.tsx, frontend/src/pages/Main.tsx, frontend/yarn.lock
- closes: #50 
- react-router-dom 라이브러리를 설치했습니다.
- 페이지 라우팅을 설정했습니다.
=> [FE] 페이지 라우팅 설정

frontend/src/components/common/Dropdown/Dropdown/Dropdown.stories.tsx, frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx, frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx, frontend/src/components/common/Dropdown/HiddenDropdown/HiddenDropdown.tsx
- closes: #36 
공통 Dropdown 구현
placeholder: string; // 선택되지 않았을 때 보여질 텍스트
options: string[];
onSelect: (option: string) => void; // 부모에게 선택된 값 전달하는 함수
defaultOption?: string; // 기본으로 설정된 옵션
width?: string; // 기본값 100%
=> [FE] 공통 Dropdown 구현

frontend/src/components/common/Modal/Modal.stories.tsx, frontend/src/components/common/Modal/Modal.styles.ts, frontend/src/components/common/Modal/Modal.tsx
- closes: #77 
- 모달 높이 옵션을 추가하였습니다.
- `height` 옵션에 원하는 크기를 기입해 모달의 높이를 지정할 수 있습니다.
=> [FE] 모달 높이 옵션 추가

frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx, frontend/src/hooks/useClickOutside.ts
- closes: #79 
useClickOutside를 구현해 바깥을 누르면 드롭다운 항목이 닫히면서도 항목을 누르면 선택되게 구현
=> [FE] 셀렉트박스 선택이 되지 않는 버그 수정

frontend/src/components/common/Button/Button.styles.ts
- closes: #83 
버튼 수정 
버튼 disabled border 스타일 수정했습니다.
=> [FE] Button disabled border 수정

frontend/src/components/common/Input/Input.stories.tsx, frontend/src/components/common/Input/Input.styles.ts, frontend/src/components/common/Input/Input.tsx
- closes: #86 
input 너비 수정
Input 컴포넌트 너비 및 높이 props  수정
=> [FE] Input width, height 프롭스 수정

backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java, backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java, backend/src/main/java/site/coduo/pairroom/dto/PairRoomDeleteRequest.java, backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java, backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
- closes: #93 
* 페어룸 삭제 API 
* 삭제 성공시 204
* 삭제 실패시 404
=> [BE] 페어룸 삭제 API 구현

.github/workflows/pull_request.yml
- closes: #100 
PR 요청이 오면 해당 요청자 제외하고 Slack 메세지로 맨션됨
=> [BE] 코드 리뷰 Github action 연동

frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
- closes: #108 
높이 5rem -> 4.8rem
더 이상의 설명은 생략한다
=> [FE] 🚑 Dropdown 높이 디자인에 맞게 수정

.github/workflows/reivew_submit_notification.yml
=> [COMMON] Githubaction & Slack 코드리뷰 연동 버스 수정

backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java, backend/src/main/java/site/coduo/pairroom/dto/PairRoomCreateRequest.java, backend/src/main/java/site/coduo/pairroom/dto/PairRoomDeleteRequest.java, backend/src/main/java/site/coduo/pairroom/dto/PairRoomReadRequest.java, backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java, backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
- closes: #45 
컨벤션에 맞게 네이밍 수정하였습니다
컨트롤러 dto의 @NotBlank 애노테이션 사용하여 검증 로직을 추가하였습니다.
=> [BE] 컨트롤러 메서드 명 수정 및 dto 검증 추가

frontend/src/apis/reference.ts, frontend/src/components/PairRoom/ReferenceCard/Reference.tsx, frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts, frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx, frontend/src/hooks/useInput.ts, frontend/src/hooks/useModal.ts
- closes: #62 
레퍼런스 링크 저장 및 추가 구현
+) useModal toggle 기능 추가했습니다
=> [FE] 레퍼런스 링크 저장 및 추가 구현

.github/workflows/be-main-cd.yml, .github/workflows/be-main-ci.yml
=> [BE] CD 스크립트 수정

.github/workflows/be-dev-ci.yml
=> [BE] CI 스크립트 수정

.github/workflows/be-main-cd.yml
=> [BE] CD 스크립트 정정

frontend/package.json, frontend/src/apis/constants.ts, frontend/webpack.config.js, frontend/yarn.lock
- closes: #133 
webpack.config.js 파일 수정 및 플러그인 설치
dotenv-webpack을 설치해 환경 파일을 인식하게 한 후 webpack.config.js 파일에서 process.env를 사용할 수 있도록 설정 수정
=> [FE] 👽 env 파일 생성을 위한 config 파일 설정

backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java, backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
=> [BE] 레퍼런스 링크 API 수정

backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java, backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java, backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
=> [BE] requestParam에서 pathVariable로 수정

.github/workflows/fe-ci.yml
- closes: #147 
CI 과정에서 유닛 테스트와 스토리북 배포 분리
=> [FE] 유닛 테스트와 스토리북 배포 분리

.github/workflows/fe-ci.yml
- closes: /
CI 파일에서 merge 브랜치 제한 목록에서 FE/dev 제거
=> [FE] CI 로직 수정

backend/src/main/java/site/coduo/pairroom/domain/PairName.java, backend/src/main/java/site/coduo/pairroom/domain/PairRoom.java, backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCode.java, backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeFactory.java, backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeStrategy.java, backend/src/main/java/site/coduo/pairroom/domain/accesscode/UUIDAccessCodeStrategy.java, backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java, backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java, backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java, backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java, backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java, backend/src/test/java/site/coduo/fake/FakeAccessCodeStrategy.java, backend/src/test/java/site/coduo/pairroom/domain/AccessCodeFactoryTest.java, backend/src/test/java/site/coduo/pairroom/domain/PairNameTest.java, backend/src/test/java/site/coduo/pairroom/domain/PairRoomTest.java, backend/src/test/java/site/coduo/pairroom/repository/PairRoomRepositoryTest.java, backend/src/test/java/site/coduo/referencelink/domain/ReferenceLinkTest.java, backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
- closes: #150 
+ 중복된 엑세스 코드 생성 시 재 생성되도록 코드 구현
+ 해당 기능에 대한 추상화
테스트 코드 및 객체 유연성을 위해 생성 로직을 Factory로 한 단계 추상화하여 구현하였음
=> [BE] 액세스 코드 중복 검증 

.github/workflows/fe-ci.yml, frontend/src/components/CreatePairRoomModal/CompleteCreatePairRoom.stories.tsx, frontend/src/components/CreatePairRoomModal/CreatePairRoomModal.tsx, frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx, frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx, frontend/src/components/PairRoom/TimerCard/TimerCard.tsx, frontend/src/components/common/Header/Header.tsx, frontend/src/hooks/PairRoom/useTimer.ts, frontend/src/pages/PairRoom/PairRoom.tsx
- closes: #158 
타이머 버그 개선
- 경과 시간을 현재 시간(Date.now)으로 계산해서 오차 줄이기
- 계산 시간 단위 0.01초로 수정해서 애니메이션 부드럽게 수정
- 타이머 default 시간을 location 으로 받아온 시간으로 수정하기
=> [FE] 타이머 버그 개선

.github/workflows/pull_request.yml, .github/workflows/review_submit_notification.yml
- closes: #184 
-  슬랙 사용자 식별자 및 슬랙 채널 실벼자 등 민감정보 Secret으로 은닉
- 별개 중개 서버 사용 없이 기능 작동하도록 actions yaml 파일 수정
=> [FE] 코드 리뷰 action yaml 수정

frontend/.stylelintrc, frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.styles.ts, frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.styles.ts, frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts, frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts, frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.styles.ts, frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts, frontend/src/components/PairRoom/PairRoomCard/Header/Header.styles.ts, frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts, frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts, frontend/src/components/PairRoomOnBoarding/InformationBox/InformationBox.styles.ts, frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.styles.ts, frontend/src/components/PairRoomOnBoarding/RoleSettingSection/RoleSettingSection.styles.ts, frontend/src/components/PairRoomOnBoarding/TimerSettingSection/TimerSettingSection.styles.ts, frontend/src/components/common/Button/Button.styles.ts, frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx, frontend/src/components/common/Header/Header.styles.ts, frontend/src/components/common/Input/Input.styles.ts, frontend/src/components/common/Modal/Body/Body.styles.ts, frontend/src/components/common/Modal/CloseButton/CloseButton.styles.ts, frontend/src/components/common/Modal/Footer/Footer.styles.ts, frontend/src/components/common/Modal/Header/Header.styles.ts, frontend/src/components/common/Modal/Modal.styles.ts, frontend/src/pages/Main/Main.styles.ts, frontend/src/pages/PairRoom/PairRoom.styles.tsx, frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
=> [FE] 컨벤션에 맞게 css 스타일 재정렬 및 표현 수정

frontend/.storybook/preview.tsx, frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.stories.tsx, frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.stories.tsx, frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx
- closes: #170 
storybook에서 wrapping 분리
=> [FE] storybook wrapping 분리하기

.github/workflows/pull_request.yml
- closes: #196 
하드 코딩된 URL로 리뷰 사이트 등록되어 있던걸 해당 PR 페이지 URL로 수정하였습니다.
=> [FE] 🐛 github action slack review URL 요청 오류 수정

.github/workflows/pull_request.yml
=> [BE] 코드 리뷰 PR URL 수정

frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx, frontend/src/components/PairRoomOnBoarding/TimerSettingSection/TimerSettingSection.tsx, frontend/src/components/common/Modal/Modal.stories.tsx
=> [FE]타입 충돌 해결

frontend/src/components/common/Header/Header.styles.ts, frontend/src/components/common/Header/Header.tsx
- closes: #205 
헤더 a 태그 모두 react-router-dom의 Link to로 변경
🤗
=> [FE] 헤더 리팩토링

frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx, frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts, frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.tsx, frontend/src/components/PairRoomOnBoarding/TimerSettingSection/TimerSettingSection.tsx, frontend/src/components/common/Button/Button.styles.ts, frontend/src/components/common/Button/Button.tsx, frontend/src/components/common/Button/Button.type.ts, frontend/src/components/common/Modal/Modal.stories.tsx, frontend/src/components/common/Modal/Modal.styles.ts, frontend/src/components/common/Modal/Modal.tsx, frontend/src/components/common/Modal/Modal.type.ts, frontend/src/hooks/Main/usePairNameInputs.test.tsx, frontend/src/pages/Main/Main.tsx
- closes: #207 
UPPER_CASE로 작성된 css 상수들 camelCase로 수정
🤗
=> [FE] UPPER_CASE로 작성된 css 상수들 camelCase로 수정

frontend/src/components/common/Input/Input.styles.ts
- closes: #204 
placeholder 색상 변경했습니다.
=> [FE] Placeholder 색 변경

frontend/src/components/PairRoomOnBoarding/FooterButtons/FooterButtons.tsx, frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.stories.tsx, frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.tsx, frontend/src/constants/PairRoomOnboarding/step.ts, frontend/src/pages/PairRoom/PairRoom.tsx, frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx, frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
- closes: #216 
- 페어룸 온보딩 페이지에서 타이머 설정을 제거했습니다.
=> [FE] 타이머 설정 제거
